Public Enum FiltroVisita
    CI_CLIENTE
    CODIGO_PROPIEDAD
    CI_EMPLEADO
    FECHA_MINIMA_VISITA
    FECHA_MINIMA_RESERVA
    FECHA_MAXIMA_VISITA
    FECHA_MAXIMA_RESERVA
    ESTADO_VISITA
End Enum
