Public Enum FiltroPropiedad
    CI_CLIENTE
    ESTADO
    OPERACION
    TIPO
    PRECIO_MINIMO
    PRECIO_MAXIMO
    HABITACIONES_MINIMO
    HABITACIONES_MAXIMO
    MTS2_MINIMO
    MTS2_MAXIMO
    CODIGO_LOCALIDAD
End Enum
